### ISSUE TITLE
Component `git_repository`

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/net#3]
## Goal

Git repositories are useful for
- Assets (maps, textures, 3D models, sound effects, soundtracks, ...)
- Flows (game modes or mechanics useful for several game modes, map logics, particle effect control, editor logics / automation, terrain generation)
- Plugins (Behaviour Implementations as WebAssembly `.wasm`)

## Component

| Property        | Component           | DataType  | SocketType | Description                                               |
|-----------------|---------------------|-----------|------------|-----------------------------------------------------------|
| `name`          | `base__named`       | `String`  | `none`     | The name.                                                 |
| `description`   | `base__describable` | `String`  | `none`     | The description.                                          |
| `url`           | `http__url`         | `String`  | `input`    | The remote url.                                           |
| `file`          | `file_file`         | `String`  | `input`    | The local path.                                           |
| `branch`        | `git__git`          | `String`  | `input`    | The git branch name. Executes a `git checkout` on change. |
||
| `remote_name`   | `git__git`          | `String`  | `input`    | The name of the remote (default: `origin`).               |
| `remote_branch` | `git__git`          | `String`  | `input`    | The name of the remote branch                             |
||
| `trigger`       | `git__git`          | `Bool`    | `input`    | Clone or pull                                             |
| `fetch`         | `git__git`          | `Bool`    | `input`    | Fetch                                                     |
| `fast_forward`  | `git__git`          | `Bool`    | `input`    | Fast-forward                                              |
| `push`          | `git__git`          | `Bool`    | `input`    | Pushes to the given remote (by default origin)            |
| `merge_from`    | `git__git`          | `String`  | `input`    | Merges the given branch into the current branch           |

This is a _building block_ for further implementation (other Components) on top:
- asset repository indexing, ...
- flow repository indexing, fetching/updating flows from the repository, flow management, uploading flows
- plugin updating, reloading, ...

## Tasks

- [x] Types
- [x] Model
- [x] Plugin
- [ ] Behaviours
  - [x] Clone (trigger `trigger`)
  - [x] Pull (trigger `trigger`)
  - [x] Fetch (trigger `fetch`)
  - [x] Fast Forward (trigger `fast_forward`)
  - [ ] Checkout (change `branch`)
  - [ ] Push (trigger `push`)
  - [ ] Merge (change `merge_from`)
